// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ig_52VHk07Ky08OE6rc1rj8-GEaoByE',
    appId: '1:461504935680:web:3f07471177ec0a8562e5e5',
    messagingSenderId: '461504935680',
    projectId: 'genui-demo-556f6',
    authDomain: 'genui-demo-556f6.firebaseapp.com',
    storageBucket: 'genui-demo-556f6.firebasestorage.app',
    measurementId: 'G-S9NFKD9XWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR8TbMu7EzjIQoAqCuWhQ1U1-djkn91p0',
    appId: '1:461504935680:android:8b4a8f7197524d7b62e5e5',
    messagingSenderId: '461504935680',
    projectId: 'genui-demo-556f6',
    storageBucket: 'genui-demo-556f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAANzbqO2rUkh4mF2xZviy73Ztd8qsfr_E',
    appId: '1:461504935680:ios:c7ce972c6294999762e5e5',
    messagingSenderId: '461504935680',
    projectId: 'genui-demo-556f6',
    storageBucket: 'genui-demo-556f6.firebasestorage.app',
    iosBundleId: 'dev.flutter.genui.genuiClient',
  );
}
